/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _CFPrefsPendingKVONotification : NSObject {
    id  oldValues;
    NSObject * source;
    id  values;
}

- (void)dealloc;

@end
