/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _CFPrefsSynchronizer : NSObject {
    struct _opaque_pthread_mutex_t { 
        long long __sig; 
        BOOL __opaque[56]; 
    }  _CFPrefsDirtySourcesLock;
    BOOL  _active;
    struct __CFSet { } * _dirtySources;
    NSObject<OS_dispatch_queue> * _synchQueue;
    NSObject<OS_dispatch_source> * _synchTimer;
}

- (id)init;

@end
