/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _CFPasteboardWeakRef : NSObject {
    id  pboardWeakRef;
}

- (void).cxx_destruct;
- (id)initWithPasteboard:(struct __CFPasteboard { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct __CFString {} *x2; id x3; struct __CFUUID {} *x4; struct __CFArray {} *x5; unsigned char x6; id x7; id x8; _Atomic unsigned long long x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned char x13; }*)arg1;
- (struct __CFPasteboard { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct __CFString {} *x2; id x3; struct __CFUUID {} *x4; struct __CFArray {} *x5; unsigned char x6; id x7; id x8; _Atomic unsigned long long x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned char x13; }*)tryRetainPasteboard;

@end
