/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _CFPasteboardEntry : NSObject {
    id  _asyncPromisor;
    const struct __CFData { } * _data;
    unsigned long long  _dataFlags;
    unsigned char  _extensionConsumed;
    const struct __CFString { } * _flavorName;
    unsigned char  _isHidden;
    unsigned char  _isPendingFlush;
    int  _itemIdentifier;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    NSObject<OS_dispatch_group> * _promiseGroup;
    _Atomic int  _promiseState;
    id  _promisor;
    NSObject<OS_xpc_object> * _promisorConnection;
    NSObject<OS_xpc_object> * _shmem;
    unsigned long long  _shmemLength;
    const struct __CFUUID { } * _uuid;
}

@property unsigned long long dataFlags;
@property unsigned char extensionConsumed;
@property (readonly) const struct __CFString { }*flavorName;
@property (readonly) unsigned char hasData;
@property (readonly) unsigned char hasLocalPromise;
@property (getter=isHidden) unsigned char hidden;
@property unsigned char isPendingFlush;
@property (readonly) int itemIdentifier;
@property (readonly) const struct __CFUUID { }*promiseUUID;
@property (readonly) unsigned char promisorExistsInCurrentProcess;

- (id)_createShmemIfNecessaryLength:(unsigned long long*)arg1;
- (void)_setLocalPromiseState:(int)arg1;
- (const struct __CFData { }*)createDataAndReturnError:(int*)arg1;
- (id)createXPCObjectWithMetadataOnly:(unsigned char)arg1;
- (unsigned long long)dataFlags;
- (void)dealloc;
- (id)description;
- (unsigned char)extensionConsumed;
- (const struct __CFString { }*)flavorName;
- (unsigned char)hasData;
- (unsigned char)hasLocalPromise;
- (id)initFromXPCObject:(id)arg1 fromConnection:(id)arg2;
- (id)initWithFlavorName:(const struct __CFString { }*)arg1 itemIdentifier:(int)arg2;
- (unsigned char)isHidden;
- (unsigned char)isPendingFlush;
- (int)itemIdentifier;
- (void)promiseDataWithBlock:(id)arg1 forPasteboard:(struct __CFPasteboard { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct __CFString {} *x2; id x3; struct __CFUUID {} *x4; struct __CFArray {} *x5; unsigned char x6; id x7; id x8; _Atomic unsigned long long x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned char x13; }*)arg2 generation:(long long)arg3;
- (const struct __CFUUID { }*)promiseUUID;
- (unsigned char)promisorExistsInCurrentProcess;
- (id)requestDataForPasteboard:(struct __CFPasteboard { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct __CFString {} *x2; id x3; struct __CFUUID {} *x4; struct __CFArray {} *x5; unsigned char x6; id x7; id x8; _Atomic unsigned long long x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned char x13; }*)arg1 generation:(long long)arg2 immediatelyAvailableResult:(struct { int x1; long long x2; struct __CFData {} *x3; unsigned long long x4; }*)arg3;
- (void)resolveClientPromisedDataWithQueue:(id)arg1 completionHandler:(id)arg2;
- (unsigned char)resolveLocalPromisedData;
- (void)setData:(struct __CFData { }*)arg1;
- (void)setDataFlags:(unsigned long long)arg1;
- (void)setExtensionConsumed:(unsigned char)arg1;
- (void)setHidden:(unsigned char)arg1;
- (void)setIsPendingFlush:(unsigned char)arg1;

// _CFPasteboardEntry (CFRemotePasteboardSupport)

- (void)promiseDataWithFetchOperation:(id)arg1;

@end
