/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _CFPasteboardClientConnectionContext : NSObject {
    struct __CFArray { } * _cleanupBlocks;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
}

- (void)addCleanupBlock:(id)arg1;
- (void)cleanup;
- (void)dealloc;
- (id)init;

@end
