/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _NSKoreanBigramKeySet_SKS : _NSSharedKeySetS

- (void)dealloc;
- (id)init;
- (id)initWithKeys:(unsigned short**)arg1 keyLenghtInBytes:(unsigned int)arg2 count:(unsigned int)arg3;
- (BOOL)isEmpty;

@end
