/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface _NSRemotePasteboardDataProvider : NSObject <UAPasteboardItemProviding> {
    struct __CFString { } * _flavorName;
    long long  _generation;
    long long  _itemIdentifier;
    NSUUID * _uuid;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *type;
@property (nonatomic, copy) NSUUID *uuid;

- (void)dealloc;
- (id)description;
- (void)getDataWithCompletionBlock:(id)arg1;
- (id)initWithGeneration:(long long)arg1 itemIdentifier:(long long)arg2 flavorName:(struct __CFString { }*)arg3;
- (void)setType:(id)arg1;
- (void)setUuid:(id)arg1;
- (id)type;
- (id)uuid;

@end
