/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface CFPDSource : NSObject {
    char * _actualPath;
    BOOL  _byHost;
    CFPrefsDaemon * _cfprefsd;
    unsigned int  _checkedForNonPrefsPlist;
    unsigned int  _dirty;
    NSObject<OS_os_transaction> * _dirtyTransaction;
    unsigned int  _disableBackup;
    struct __CFString { } * _domain;
    int  _fileProtectionClass;
    short  _generationShmemIndex;
    unsigned int  _handlingRequest;
    unsigned int  _lastEgid;
    unsigned int  _lastEuid;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    BOOL  _managed;
    BOOL  _managedUsesContainer;
    unsigned int  _neverCache;
    struct __CFSet { } * _observingConnections;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _observingConnectionsLock;
    NSObject<OS_xpc_object> * _pendingChangesQueue;
    unsigned long long  _pendingChangesSize;
    CFPDDataBuffer * _plist;
    unsigned int  _restrictedReadability;
    struct __CFString { } * _uncanonicalizedPathCache;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _uncanonicalizedPathCacheLock;
    struct __CFString { } * _userName;
    unsigned int  _waitingForDeviceUnlock;
    BOOL  _watchingParentDirectory;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _writeLock;
}

- (id)acceptMessage:(id)arg1;
- (void)asyncNotifyObserversOfWriteFromConnection:(id)arg1 message:(id)arg2;
- (BOOL)byHost;
- (void)cacheActualPath;
- (void)cleanUpAfterAcceptingMessage:(id)arg1;
- (struct __CFString { }*)cloudConfigurationPath;
- (struct __CFString { }*)container;
- (id)copyPropertyListValidatingPlist:(BOOL)arg1;
- (id)copyPropertyListWithoutDrainingPendingChangesValidatingPlist:(BOOL)arg1;
- (struct __CFString { }*)copyUncanonicalizedPath;
- (id)createDiskWriteShouldPerformSynchronously:(BOOL*)arg1;
- (void)dealloc;
- (struct __CFString { }*)debugDump;
- (id)description;
- (struct __CFString { }*)domain;
- (void)drainPendingChanges;
- (BOOL)enqueueNewKey:(id)arg1 value:(id)arg2 encoding:(int)arg3 inBatch:(BOOL)arg4;
- (void)finishedNonRequestWriteWithError:(int)arg1;
- (unsigned long long)hash;
- (id)initWithDomain:(struct __CFString { }*)arg1 userName:(struct __CFString { }*)arg2 byHost:(BOOL)arg3 managed:(BOOL)arg4 shmemIndex:(short)arg5 daemon:(id)arg6;
- (BOOL)isEqual:(id)arg1;
- (void)lockedAsync:(id)arg1;
- (void)lockedSync:(id)arg1;
- (BOOL)managed;
- (void)observingConnectionWasInvalidated:(id)arg1;
- (void)processEndOfMessageIntendingToRemoveSource:(BOOL*)arg1;
- (void)respondToFileWrittenToBehindOurBack;
- (void)setDirty:(BOOL)arg1;
- (void)setManagedPreferencesUseContainer:(BOOL)arg1;
- (void)setUncanonicalizedPathCached:(BOOL)arg1;
- (short)shmemIndex;
- (void)syncWriteToDisk;
- (void)syncWriteToDiskAndFlushCacheForReason:(struct __CFString { }*)arg1;
- (void)updateShmemEntry;
- (struct __CFString { }*)user;
- (int)validateMessage:(id)arg1 withNewKey:(id)arg2 newValue:(id)arg3 plistIsAvailableToRead:(BOOL)arg4 containerPath:(const char *)arg5 diagnosticMessage:(const char **)arg6;

@end
