/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface CFPDSourceLookUpKey : NSObject {
    struct __CFString { } * cloudPath;
    struct __CFString { } * uncanonicalizedPath;
}

- (void)dealloc;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@end
