/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface CFPrefsDaemon : NSObject {
    NSObject<OS_xpc_object> * _agentConnections;
    NSObject<OS_dispatch_queue> * _agentQueue;
    struct { 
        unsigned long long buckets[64]; 
    }  _deadManagedSourceBitSet;
    struct __CFSet { } * _deadSourceShmemIndexes;
    NSObject<OS_xpc_object> * _listener;
    const char * _name;
    int  _role;
    _Atomic unsigned int * _shmem;
    struct __CFSet { } * _sourceCache;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _sourceCacheLock;
    struct __CFBag { } * _sourceCacheUsageCounts;
    BOOL  _testMode;
}

@end
