/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface CFPrefsPlistSource : CFPrefsSource {
    _Atomic BOOL  _avoidsDaemonCache;
    _Atomic BOOL  _byteCountLimitExceeded;
    _Atomic BOOL  _checkedInvalidHome;
    _Atomic BOOL  _directMode;
    _Atomic int  _fileProtectionClass;
    _Atomic BOOL  _isByHost;
    _Atomic BOOL  _lastWriteFailed;
    _Atomic struct __CFDictionary {} * _locallySetDict;
    _Atomic BOOL  _observing;
    _Atomic BOOL  _readonly;
    _Atomic BOOL  _restrictedAccess;
    _Atomic BOOL  _volatile;
    _Atomic char * accessPath;
    struct __CFString { } * container;
    struct __CFString { } * domainIdentifier;
    struct __CFString { } * userIdentifier;
}

- (void)alreadylocked_clearCache;
- (struct __CFDictionary { }*)alreadylocked_copyDictionary;
- (struct __CFArray { }*)alreadylocked_copyKeyList;
- (void*)alreadylocked_copyValueForKey:(struct __CFString { }*)arg1;
- (id)alreadylocked_createObserverUpdateMessageWithOperation:(int)arg1 forRole:(int*)arg2;
- (long long)alreadylocked_generationCount;
- (void)alreadylocked_setPrecopiedValues:(const void**)arg1 forKeys:(const struct __CFString {}**)arg2 count:(long long)arg3 from:(id)arg4;
- (int)alreadylocked_updateObservingRemoteChanges;
- (struct __CFString { }*)container;
- (void*)copyValueForKey:(struct __CFString { }*)arg1;
- (id)createRequestNewContentMessageForDaemon:(int)arg1;
- (id)createSynchronizeMessage;
- (void)dealloc;
- (struct __CFString { }*)domainIdentifier;
- (long long)generationCount;
- (void)handleReply:(id)arg1 toRequestNewDataMessage:(id)arg2 onConnection:(id)arg3 retryCount:(int)arg4 error:(BOOL*)arg5;
- (id)initWithDomain:(struct __CFString { }*)arg1 user:(struct __CFString { }*)arg2 byHost:(BOOL)arg3 containerPath:(struct __CFString { }*)arg4 containingPreferences:(id)arg5;
- (BOOL)isByHost;
- (BOOL)isDirectModeEnabled;
- (BOOL)isVolatile;
- (void)setAccessRestricted:(BOOL)arg1;
- (void)setDaemonCacheEnabled:(BOOL)arg1;
- (void)setFileProtectionClass:(int)arg1;
- (BOOL)synchronize;
- (void)transitionIntoDirectModeIfNeededWithRetryBlock:(id)arg1;
- (struct __CFString { }*)userIdentifier;

@end
