/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSCache : NSObject {
    id  _delegate;
    void * _private;
    void * _reserved;
}

@property unsigned long long countLimit;
@property <NSCacheDelegate> *delegate;
@property BOOL evictsObjectsWithDiscardedContent;
@property (copy) NSString *name;
@property unsigned long long totalCostLimit;

// Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

- (void)__apply:(id)arg1;
- (id)allObjects;
- (unsigned long long)countLimit;
- (void)dealloc;
- (id)delegate;
- (BOOL)evictsObjectsWhenApplicationEntersBackground;
- (BOOL)evictsObjectsWithDiscardedContent;
- (id)init;
- (unsigned long long)minimumObjectCount;
- (id)name;
- (id)objectForKey:(id)arg1;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)setCountLimit:(unsigned long long)arg1;
- (void)setDelegate:(id)arg1;
- (void)setEvictsObjectsWhenApplicationEntersBackground:(BOOL)arg1;
- (void)setEvictsObjectsWithDiscardedContent:(BOOL)arg1;
- (void)setMinimumObjectCount:(unsigned long long)arg1;
- (void)setName:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 cost:(unsigned long long)arg3;
- (void)setTotalCostLimit:(unsigned long long)arg1;
- (unsigned long long)totalCostLimit;

// Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

// NSCache (NSPrivate_Enumeration)

- (id)mapTableRepresentation;

@end
