/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSConstantData : NSData {
    const char * _bytes;
    unsigned long long  _length;
}

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)new;

- (BOOL)_copyWillRetain;
- (BOOL)_isCompact;
- (BOOL)_isDeallocating;
- (BOOL)_providesConcreteBacking;
- (BOOL)_tryRetain;
- (id)autorelease;
- (const void*)bytes;
- (id)copy;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithBytes:(const void*)arg1 length:(unsigned long long)arg2;
- (id)initWithBytes:(void*)arg1 length:(unsigned long long)arg2 copy:(BOOL)arg3 deallocator:(id)arg4;
- (id)initWithBytesNoCopy:(void*)arg1 length:(unsigned long long)arg2;
- (id)initWithBytesNoCopy:(void*)arg1 length:(unsigned long long)arg2 freeWhenDone:(BOOL)arg3;
- (id)initWithData:(id)arg1;
- (unsigned long long)length;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;

@end
