/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSDictionary : NSObject <CUByteCodable, NSCopying, NSFastEnumeration, NSFetchRequestResult, NSMutableCopying, NSSecureCoding>

@property (nonatomic, readonly, copy) NSDictionary *ANQPResponse;
@property (nonatomic, readonly, copy) NSString *BSSID;
@property (nonatomic, readonly, copy) NSString *HESSID;
@property (nonatomic, readonly, copy) NSArray *NAIRealmNameList;
@property (nonatomic, readonly) NSArray *RSNAuthSelectors;
@property (nonatomic, readonly) unsigned long long RSNBroadcastCipher;
@property (nonatomic, readonly) int RSNCapabilities;
@property (nonatomic, readonly) unsigned long long RSNMulticastCipher;
@property (nonatomic, readonly) NSArray *RSNUnicastCiphers;
@property (nonatomic, readonly) long long RSSI;
@property (nonatomic, readonly, copy) NSData *SSID;
@property (nonatomic, readonly) long long WAPISubtype;
@property (nonatomic, readonly) NSArray *WPAAuthSelectors;
@property (nonatomic, readonly) unsigned long long WPAMulticastCipher;
@property (nonatomic, readonly) NSArray *WPAUnicastCiphers;
@property (nonatomic, readonly) int accessNetworkType;
@property (nonatomic, readonly) long long airPortBaseStationModel;
@property (nonatomic, readonly) long long beaconInterval;
@property (nonatomic, readonly, copy) NSString *bluetoothMAC;
@property (nonatomic, readonly) unsigned long long cacheAge;
@property (nonatomic, readonly, copy) NSArray *cellularNetworkInfo;
@property (nonatomic, readonly, copy) CWFChannel *channel;
@property (nonatomic, readonly, copy) NSDictionary *channelInfo;
@property (readonly) unsigned long long count;
@property (nonatomic, readonly, copy) NSString *countryCode;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *deviceID;
@property (nonatomic, readonly, copy) NSString *displayName;
@property (nonatomic, readonly, copy) NSArray *domainNameList;
@property (nonatomic, readonly) unsigned short fileHFSFlags;
@property (nonatomic, readonly) unsigned long long fileHFSResourceForkSize;
@property (nonatomic, readonly, copy) NSString *friendlyName;
@property (nonatomic, readonly) BOOL hasAppleIE;
@property (nonatomic, readonly) BOOL hasInterworkingIE;
@property (nonatomic, readonly) BOOL hasRSNIE;
@property (nonatomic, readonly) BOOL hasWPAIE;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSData *informationElementData;
@property (nonatomic, readonly) BOOL isAdditionalStepRequiredForAccess;
@property (nonatomic, readonly) BOOL isAppleSWAP;
@property (nonatomic, readonly) BOOL isEmergencyServicesReachable;
@property (nonatomic, readonly) BOOL isIBSS;
@property (nonatomic, readonly) BOOL isInternetAccessible;
@property (nonatomic, readonly) BOOL isPasspoint;
@property (nonatomic, readonly) BOOL isPersonalHotspot;
@property (nonatomic, readonly) BOOL isUnauthenticatedEmergencyServiceAccessible;
@property (nonatomic, readonly) BOOL isUnconfiguredAirPortBaseStation;
@property (nonatomic, readonly) BOOL isUnconfiguredDevice;
@property (nonatomic, readonly, copy) NSString *manufacturerName;
@property (nonatomic, readonly, copy) NSString *modelName;
@property (nonatomic, readonly) long long noise;
@property (nonatomic, readonly, copy) NSArray *operatorFriendlyNameList;
@property (nonatomic, readonly, copy) NSString *primaryMAC;
@property (nonatomic, readonly) BOOL providesInternetAccess;
@property (nonatomic, readonly, copy) NSArray *roamingConsortiumList;
@property (readonly) Class superclass;
@property (nonatomic, readonly) int supportedPHYModes;
@property (nonatomic, readonly) unsigned long long supportedSecurityTypes;
@property (nonatomic, readonly) BOOL supports2GHzNetworks;
@property (nonatomic, readonly) BOOL supports5GHzNetworks;
@property (nonatomic, readonly) BOOL supportsAirPlay;
@property (nonatomic, readonly) BOOL supportsAirPlay2;
@property (nonatomic, readonly) BOOL supportsAirPrint;
@property (nonatomic, readonly) BOOL supportsCarPlay;
@property (nonatomic, readonly) BOOL supportsHomeKit;
@property (nonatomic, readonly) BOOL supportsHomeKit2;
@property (nonatomic, readonly) BOOL supportsMFi;
@property (nonatomic, readonly) BOOL supportsMFiHardwareAuth;
@property (nonatomic, readonly) BOOL supportsSecureWAC;
@property (nonatomic, readonly) BOOL supportsSoftwareCertAuth;
@property (nonatomic, readonly) BOOL supportsSoftwareTokenAuth;
@property (nonatomic, readonly) BOOL supportsWPS;
@property (nonatomic, readonly) BOOL supportsWoW;
@property (nonatomic, readonly) BOOL supportsiAPOverWiFi;
@property (nonatomic, readonly) long long venueGroup;
@property (nonatomic, readonly) long long venueType;

// Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)dictionary;
+ (id)dictionaryWithDictionary:(id)arg1;
+ (id)dictionaryWithDictionary:(id)arg1 copyItems:(BOOL)arg2;
+ (id)dictionaryWithObject:(id)arg1 forKey:(id)arg2;
+ (id)dictionaryWithObjects:(id)arg1 forKeys:(id)arg2;
+ (id)dictionaryWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
+ (id)dictionaryWithObjectsAndKeys:(id)arg1;
+ (id)newDictionaryWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
+ (BOOL)supportsSecureCoding;

- (void)__apply:(int (*)arg1 context:(void*)arg2;
- (BOOL)__getValue:(id*)arg1 forKey:(id)arg2;
- (id)_cfMutableCopy;
- (unsigned long long)_cfTypeID;
- (id)allKeys;
- (id)allKeysForObject:(id)arg1;
- (id)allObjects;
- (id)allValues;
- (BOOL)containsKey:(id)arg1;
- (BOOL)containsObject:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (unsigned long long)count;
- (unsigned long long)countByEnumeratingWithState:(struct { unsigned long long x1; id *x2; unsigned long long *x3; unsigned long long x4[5]; }*)arg1 objects:(id*)arg2 count:(unsigned long long)arg3;
- (unsigned long long)countForKey:(id)arg1;
- (unsigned long long)countForObject:(id)arg1;
- (id)description;
- (id)descriptionWithLocale:(id)arg1;
- (id)descriptionWithLocale:(id)arg1 indent:(unsigned long long)arg2;
- (void)encodeWithCoder:(id)arg1;
- (void)enumerateKeysAndObjectsUsingBlock:(id)arg1;
- (void)enumerateKeysAndObjectsWithOptions:(unsigned long long)arg1 usingBlock:(id)arg2;
- (void)getKeys:(id*)arg1;
- (void)getObjects:(id*)arg1;
- (void)getObjects:(id*)arg1 andKeys:(id*)arg2;
- (void)getObjects:(id*)arg1 andKeys:(id*)arg2 count:(unsigned long long)arg3;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1 copyItems:(BOOL)arg2;
- (id)initWithObject:(id)arg1 forKey:(id)arg2;
- (id)initWithObjects:(id)arg1 forKeys:(id)arg2;
- (id)initWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
- (id)initWithObjectsAndKeys:(id)arg1;
- (id)invertedDictionary;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToDictionary:(id)arg1;
- (BOOL)isNSDictionary__;
- (id)keyEnumerator;
- (id)keyOfEntryPassingTest:(id)arg1;
- (id)keyOfEntryWithOptions:(unsigned long long)arg1 passingTest:(id)arg2;
- (id)keysOfEntriesPassingTest:(id)arg1;
- (id)keysOfEntriesWithOptions:(unsigned long long)arg1 passingTest:(id)arg2;
- (id)keysSortedByValueUsingComparator:(id)arg1;
- (id)keysSortedByValueUsingSelector:(SEL)arg1;
- (id)keysSortedByValueWithOptions:(unsigned long long)arg1 usingComparator:(id)arg2;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)objectEnumerator;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectsForKeys:(id)arg1 notFoundMarker:(id)arg2;

// NSDictionary (NSSharedKeySetDictionary)

+ (id)sharedKeySetForKeys:(id)arg1;

// Image: /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera

- (id)keypathValueDictionary;
- (id)keypathValueDictionary:(id)arg1;
- (id)makeSerializable;

// Image: /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts

// NSDictionary (Accounts)

- (id)ac_mapValues:(id)arg1;
- (id)ac_mapValuesNullable:(id)arg1;

// Image: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

// NSDictionary (NSEqualObjectsForKeys)

- (BOOL)isEqualToDictionary:(id)arg1 forKeys:(id)arg2;

// Image: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit

// NSDictionary (CKContainerAssignment)

- (void)CKAssignToContainerWithID:(id)arg1;

// NSDictionary (CKPropertiesDescription)

- (id)CKDescriptionPropertiesWithPublic:(BOOL)arg1 private:(BOOL)arg2 shouldExpand:(BOOL)arg3;
- (id)CKSingleLineDescription;

// NSDictionary (CKUtilsAdditions)

- (id)CKFirstUrlForKeys:(id)arg1;

// Image: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices

// NSDictionary (LSNormalizePluginDictionary)

- (id)ls_insertExtensionPointVersion:(id)arg1;
- (id)ls_updatePlistKeys;

// NSDictionary (LSPluginQueryAdditions)

- (unsigned long long)ls_hashQuery;
- (id)ls_parseQueryForIdentifiers:(id)arg1;

// NSDictionary (LSPluginSDKResolutionAdditions)

- (id)ls_resolvePlugInKitInfoPlistWithDictionary:(id)arg1;

// NSDictionary (LSRecordBuilderAdditions)

- (BOOL)_LS_BoolForKey:(id)arg1;
- (unsigned long long)_LS_integerForKey:(id)arg1;

// Image: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList

// NSDictionary (SFL)

- (BOOL)_SFL_boolForKey:(id)arg1;
- (BOOL)_SFL_containsEntriesFromDictionary:(id)arg1;
- (id)_SFL_dataForKey:(id)arg1;
- (id)_SFL_dictionaryByRemovingNSNullValues;
- (id)_SFL_dictionaryForKey:(id)arg1;
- (long long)_SFL_integerForKey:(id)arg1;
- (id)_SFL_numberOrNullForKey:(id)arg1;
- (id)_SFL_stringForKey:(id)arg1;

// Image: /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider

// NSDictionary (FPFrameworkAdditions)

- (id)fp_filter:(id)arg1;
- (id)fp_removingObjectsNotKindOfClasses:(id)arg1;

// NSDictionary (FPMoveOperation)

- (id)fp_copyItemKeysAndValuesUnwrappedAndKeyMap:(id)arg1;
- (id)fp_copyItemKeysUnwrappedAndKeyMap:(id)arg1;

// Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

// NSDictionary (NSDeprecatedKeyValueCoding)

- (void)takeValue:(id)arg1 forKey:(id)arg2;

// NSDictionary (NSDictionary)

+ (id)dictionaryWithContentsOfFile:(id)arg1;
+ (id)dictionaryWithContentsOfURL:(id)arg1;
+ (id)dictionaryWithContentsOfURL:(id)arg1 error:(id*)arg2;
+ (id)newWithContentsOf:(id)arg1 immutable:(BOOL)arg2;
+ (id)newWithContentsOf:(id)arg1 immutable:(BOOL)arg2 error:(id*)arg3;
+ (BOOL)supportsSecureCoding;

- (id)_stringToWrite;
- (Class)classForCoder;
- (id)descriptionInStringsFileFormat;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 error:(id*)arg2;
- (BOOL)writeToFile:(id)arg1 atomically:(BOOL)arg2;
- (BOOL)writeToURL:(id)arg1 atomically:(BOOL)arg2;
- (BOOL)writeToURL:(id)arg1 error:(id*)arg2;

// NSDictionary (NSDictionaryPortCoding)

- (id)replacementObjectForPortCoder:(id)arg1;

// NSDictionary (NSFileAttributes)

- (id)fileCreationDate;
- (BOOL)fileExtensionHidden;
- (id)fileGroupOwnerAccountID;
- (id)fileGroupOwnerAccountName;
- (unsigned long long)fileGroupOwnerAccountNumber;
- (unsigned int)fileHFSCreatorCode;
- (unsigned int)fileHFSTypeCode;
- (BOOL)fileIsAppendOnly;
- (BOOL)fileIsImmutable;
- (id)fileModificationDate;
- (id)fileOwnerAccountID;
- (id)fileOwnerAccountName;
- (unsigned long long)fileOwnerAccountNumber;
- (unsigned long long)filePosixPermissions;
- (unsigned long long)fileSize;
- (unsigned long long)fileSystemFileNumber;
- (long long)fileSystemNumber;
- (id)fileType;

// NSDictionary (NSKeyValueCoding)

- (id)storedValueForKey:(id)arg1;
- (void)takeStoredValue:(id)arg1 forKey:(id)arg2;
- (id)valueForKey:(id)arg1;
- (id)valueForKeyPath:(id)arg1;

// NSDictionary (NSScriptAppleEventConversion)

+ (id)_scriptingDictionaryOfType:(id)arg1 withDescriptor:(id)arg2;

- (id)_scriptingDescriptorOfRecordType:(id)arg1 orReasonWhyNot:(id*)arg2;

// NSDictionary (NSScriptLegacyPropertyListParsing)

- (id)_scriptClassTerminologyForName:(id)arg1;
- (id)_scriptCommandTerminologyForName:(id)arg1;
- (BOOL)_scriptFlagsForKey:(id)arg1 containFlag:(id)arg2;
- (BOOL)_scriptIsYesForKey:(id)arg1 default:(BOOL)arg2;
- (id)_scriptTerminologyDescription;
- (id)_scriptTerminologyName;
- (id)_scriptTerminologyNameOrNames;
- (id)_scriptTerminologyPluralName;

// NSDictionary (NSURLExtras)

- (int)_web_intForKey:(id)arg1;
- (id)_web_numberForKey:(id)arg1;
- (id)_web_objectForMIMEType:(id)arg1;
- (id)_web_stringForKey:(id)arg1;

// Image: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore

// NSDictionary (CAMLWriter)

- (id)CAMLType;
- (void)encodeWithCAMLWriter:(id)arg1;

// NSDictionary (CARenderValue)

- (struct KeyValueArray { int (**x1)(); struct Atomic { struct { int x_1_2_1; } x_2_1_1; } x2; unsigned int x3; struct Object {} *x4[1]; }*)CA_copyRenderKeyValueArray;

// Image: /System/Library/PrivateFrameworks/AXCoreUtilities.framework/Versions/A/AXCoreUtilities

// NSDictionary (AXExtras)

- (id)ax_deepMutableCopy;

// Image: /System/Library/PrivateFrameworks/AccessibilitySharedSupport.framework/Versions/A/AccessibilitySharedSupport

// NSDictionary (ClassChecking)

- (id)axssDecodeArrayOfClass:(Class)arg1 forKey:(id)arg2;
- (BOOL)axssDecodeBoolForKey:(id)arg1;
- (id)axssDecodeObjectOfClass:(Class)arg1 forKey:(id)arg2;

// Image: /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit

// NSDictionary (AuthKit)

+ (id)ak_dictionaryWithResponseData:(id)arg1;
+ (id)ak_jsonDictionaryWithResponseData:(id)arg1;

- (id)_ak_truncatedTokensCopy;
- (id)ak_mapObjects:(id)arg1;
- (id)ak_mapObjectsNullable:(id)arg1;
- (id)ak_redactedCopy;
- (id)ak_toJSONString;
- (id)ak_urlQueryString;

// Image: /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard

// NSDictionary (BaseBoard)

- (BOOL)bs_boolForKey:(id)arg1;
- (id)bs_dictionaryByAddingEntriesFromDictionary:(id)arg1;
- (void)bs_each:(id)arg1;
- (id)bs_filter:(id)arg1;
- (id)bs_safeArrayForKey:(id)arg1;
- (id)bs_safeDictionaryForKey:(id)arg1;
- (id)bs_safeNumberForKey:(id)arg1;
- (id)bs_safeObjectForKey:(id)arg1 ofType:(Class)arg2;
- (id)bs_safeStringForKey:(id)arg1;
- (id)bs_safeURLForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils

// NSDictionary (CUByteCodable)

+ (id)createWithBytesNoCopy:(void*)arg1 length:(unsigned long long)arg2 error:(id*)arg3;

- (const char *)encodedBytesAndReturnLength:(unsigned long long*)arg1 error:(id*)arg2;
- (id)encodedDataAndReturnError:(id*)arg1;

// Image: /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi

// NSDictionary (ScanRecord)

- (id)ANQPResponse;
- (id)BSSID;
- (id)HESSID;
- (id)NAIRealmNameList;
- (id)RSNAuthSelectors;
- (unsigned long long)RSNBroadcastCipher;
- (int)RSNCapabilities;
- (unsigned long long)RSNMulticastCipher;
- (id)RSNUnicastCiphers;
- (long long)RSSI;
- (id)SSID;
- (long long)WAPISubtype;
- (id)WPAAuthSelectors;
- (unsigned long long)WPAMulticastCipher;
- (id)WPAUnicastCiphers;
- (id)__WAPIPolicy;
- (int)accessNetworkType;
- (long long)airPortBaseStationModel;
- (long long)beaconInterval;
- (id)bluetoothMAC;
- (unsigned long long)cacheAge;
- (id)cellularNetworkInfo;
- (id)channel;
- (id)channelInfo;
- (id)countryCode;
- (id)deviceID;
- (id)displayName;
- (id)domainNameList;
- (id)friendlyName;
- (BOOL)hasAppleIE;
- (BOOL)hasInterworkingIE;
- (BOOL)hasRSNIE;
- (BOOL)hasWPAIE;
- (id)informationElementData;
- (BOOL)isAdditionalStepRequiredForAccess;
- (BOOL)isAppleSWAP;
- (BOOL)isEmergencyServicesReachable;
- (BOOL)isIBSS;
- (BOOL)isInternetAccessible;
- (BOOL)isPasspoint;
- (BOOL)isPersonalHotspot;
- (BOOL)isUnauthenticatedEmergencyServiceAccessible;
- (BOOL)isUnconfiguredAirPortBaseStation;
- (BOOL)isUnconfiguredDevice;
- (id)manufacturerName;
- (id)modelName;
- (long long)noise;
- (id)operatorFriendlyNameList;
- (id)primaryMAC;
- (BOOL)providesInternetAccess;
- (id)roamingConsortiumList;
- (int)supportedPHYModes;
- (unsigned long long)supportedSecurityTypes;
- (BOOL)supports2GHzNetworks;
- (BOOL)supports5GHzNetworks;
- (BOOL)supportsAirPlay;
- (BOOL)supportsAirPlay2;
- (BOOL)supportsAirPrint;
- (BOOL)supportsCarPlay;
- (BOOL)supportsHomeKit;
- (BOOL)supportsHomeKit2;
- (BOOL)supportsMFi;
- (BOOL)supportsMFiHardwareAuth;
- (BOOL)supportsSecureWAC;
- (BOOL)supportsSoftwareCertAuth;
- (BOOL)supportsSoftwareTokenAuth;
- (BOOL)supportsWPS;
- (BOOL)supportsWoW;
- (BOOL)supportsiAPOverWiFi;
- (long long)venueGroup;
- (long long)venueType;

// Image: /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages

// NSDictionary (BetterAccessors)

- (id)stringForKey:(id)arg1;

// NSDictionary (DictionaryExtensions)

- (BOOL)boolForKey:(id)arg1;
- (BOOL)boolForKey:(id)arg1 defaultValue:(BOOL)arg2;
- (int)integerForKey:(id)arg1;

// NSDictionary (NSBundleExtras)

- (id)bundleIdentifierFromInfoDictionary;
- (id)shortVersionFromInfoDictionary;

// NSDictionary (XPCServiceExtras)

- (id)taoDeepMutableCopy;
- (void)taoDeepMutableRelease;

// Image: /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices

// NSDictionary (GEOURLExtras)

- (id)_placeOrCurrentLocation:(BOOL*)arg1;

// NSDictionary (GEOXPCUtil)

+ (id)_geo_dictionaryFromXPCObject:(id)arg1;
+ (id)_geo_replyDictionaryForError:(id)arg1 key:(id)arg2;

- (id)_geo_errorForKey:(id)arg1;
- (id)_geo_newXPCObject;

// Image: /System/Library/PrivateFrameworks/IMFoundation.framework/Versions/A/IMFoundation

+ (id)dictionaryWithKeyArray:(id)arg1 defaultValue:(id)arg2;
+ (id)dictionaryWithPlistData:(id)arg1;

- (id)__imDeepCopy;
- (id)__imDictionaryByFilteringWithBlock:(id)arg1;
- (BOOL)__imIsMutable;
- (id)_arrayForKey:(id)arg1;
- (id)_dataForKey:(id)arg1;
- (id)_dictionaryForKey:(id)arg1;
- (id)_numberForKey:(id)arg1;
- (id)_stringForKey:(id)arg1;
- (id)dictionaryFromChanges:(id)arg1;
- (unsigned short)fileHFSFlags;
- (unsigned long long)fileHFSResourceForkSize;
- (id)keysOfChangedEntriesComparedTo:(id)arg1;
- (id)plistData;

// Image: /System/Library/PrivateFrameworks/IconFoundation.framework/Versions/A/IconFoundation

// NSDictionary (IconFoundationAdditions)

- (id)_IF_arrayForKey:(id)arg1;
- (id)_IF_arrayForKeys:(id)arg1;
- (BOOL)_IF_boolForKey:(id)arg1;
- (BOOL)_IF_boolForKey:(id)arg1 defaultValue:(BOOL)arg2;
- (BOOL)_IF_boolForKeys:(id)arg1;
- (BOOL)_IF_boolForKeys:(id)arg1 defaultValue:(BOOL)arg2;
- (id)_IF_dataForKey:(id)arg1;
- (id)_IF_dictionaryAddingEntriesFromDictionary:(id)arg1;
- (id)_IF_dictionaryForKey:(id)arg1;
- (id)_IF_dictionaryForKeys:(id)arg1;
- (id)_IF_numberForKey:(id)arg1;
- (id)_IF_numberForKeys:(id)arg1;
- (id)_IF_objectOfClass:(Class)arg1 forKey:(id)arg2;
- (id)_IF_objectOfClass:(Class)arg1 forKeys:(id)arg2;
- (id)_IF_stringForKey:(id)arg1;
- (id)_IF_stringForKeys:(id)arg1;

// Image: /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices

// NSDictionary (ISCompositorResourceProvider)

- (id)_IS_resourceNamed:(id)arg1;

// Image: /System/Library/PrivateFrameworks/RunningBoardServices.framework/Versions/A/RunningBoardServices

// NSDictionary (RunningBoard)

- (id)entriesToStringWithIndent:(int)arg1 debug:(BOOL)arg2;

// Image: /System/Library/PrivateFrameworks/SystemAdministration.framework/Versions/A/SystemAdministration

// NSDictionary (cXMLDataConvertor)

+ (id)dictionaryFromXMLString:(id)arg1;

- (id)XMLString;

// Image: /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation

// NSDictionary (UICollectionAdditions)

- (BOOL)_boolForKey:(id)arg1;

@end
