/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSInvocation : NSObject {
    NSMutableArray * _container;
    void * _frame;
    unsigned int  _magic;
    BOOL * _replacedByPointerBacking;
    unsigned char  _retainedArgs;
    void * _retdata;
    NSMethodSignature * _signature;
    unsigned char  _stackAllocated;
}

@property (readonly) BOOL argumentsRetained;
@property (readonly, retain) NSMethodSignature *methodSignature;
@property SEL selector;
@property id target;

// Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

+ (id)_invocationWithMethodSignature:(id)arg1 frame:(void*)arg2;
+ (id)invocationWithMethodSignature:(id)arg1;
+ (unsigned long long)requiredStackSizeForSignature:(id)arg1;

- (void)_addAttachedObject:(id)arg1;
- (id)_initWithMethodSignature:(id)arg1 frame:(void*)arg2 buffer:(void*)arg3 size:(unsigned long long)arg4;
- (BOOL)argumentsRetained;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (void)getArgument:(void*)arg1 atIndex:(long long)arg2;
- (void)getReturnValue:(void*)arg1;
- (id)init;
- (void)invoke;
- (void)invokeSuper;
- (void)invokeUsingIMP:(int (*)arg1;
- (void)invokeWithTarget:(id)arg1;
- (id)methodSignature;
- (void)retainArguments;
- (SEL)selector;
- (void)setArgument:(void*)arg1 atIndex:(long long)arg2;
- (void)setReturnValue:(void*)arg1;
- (void)setSelector:(SEL)arg1;
- (void)setTarget:(id)arg1;
- (id)target;

// Image: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit

// NSInvocation (CKExtensions)

- (void)CKInvokeAndNilOutReplyBlockWithError:(id)arg1 forProtocol:(id)arg2;
- (void)CKIterateArgumentsForIndexRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 primitiveTypeBlock:(id)arg2 objectBlock:(id)arg3 blockBlock:(id)arg4;

// Image: /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider

// NSInvocation (FPCopy)

- (id)fp_copy;

// NSInvocation (FPExtensions)

- (void)fp_sanitizeError;
- (void)fp_transformArgumentAtIndex:(unsigned long long)arg1 withBlock:(id)arg2;
- (void)fp_zeroOutReplyBlockArgumentsWithError:(id)arg1;

// Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

// NSInvocation (NSInvocationDebugDescription)

- (id)debugDescription;

// NSInvocation (NSXPCConnectionExtensions)

- (BOOL)_hasBlockArgument;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;

// Image: /System/Library/PrivateFrameworks/IMFoundation.framework/Versions/A/IMFoundation

- (BOOL)wantsReturnValue;

@end
