/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSInputStream : NSStream {
    unsigned char  _reserved;
}

@property (readonly) BOOL hasBytesAvailable;

// Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

// NSInputStream (NSCFInputStreamAdditions)

- (struct { long long x1; int x2; })_cfStreamError;

// NSInputStream (NSInputStream)

+ (id)allocWithZone:(struct _NSZone { }*)arg1;
+ (id)inputStreamWithData:(id)arg1;
+ (id)inputStreamWithFileAtPath:(id)arg1;
+ (id)inputStreamWithURL:(id)arg1;

- (unsigned long long)_cfTypeID;
- (void)dealloc;
- (BOOL)getBuffer:(char **)arg1 length:(unsigned long long*)arg2;
- (BOOL)hasBytesAvailable;
- (id)initWithData:(id)arg1;
- (id)initWithURL:(id)arg1;
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;

@end
