/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 */

@interface NSMutableDictionary : NSDictionary

// Image: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

+ (id)dictionaryWithCapacity:(unsigned long long)arg1;

- (void)__addObject:(id)arg1 forKey:(id)arg2;
- (void)__setObject:(id)arg1 forKey:(id)arg2;
- (void)_mutate;
- (void)addEntriesFromDictionary:(id)arg1;
- (void)addObject:(id)arg1 forKey:(id)arg2;
- (void)addObjects:(id)arg1 forKeys:(id)arg2;
- (void)addObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)initWithObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
- (void)invert;
- (void)removeAllObjects;
- (void)removeEntriesInDictionary:(id)arg1;
- (void)removeEntriesPassingTest:(id)arg1;
- (void)removeEntriesWithOptions:(unsigned long long)arg1 passingTest:(id)arg2;
- (void)removeKeysForObject:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (void)removeObjectsForKeys:(id)arg1;
- (void)replaceObject:(id)arg1 forKey:(id)arg2;
- (void)replaceObjects:(id)arg1 forKeys:(id)arg2;
- (void)replaceObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;
- (void)setDictionary:(id)arg1;
- (void)setEntriesFromDictionary:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObjects:(id)arg1 forKeys:(id)arg2;
- (void)setObjects:(const id*)arg1 forKeys:(const id*)arg2 count:(unsigned long long)arg3;

// NSMutableDictionary (NSSharedKeySetDictionary)

+ (id)dictionaryWithSharedKeySet:(id)arg1;

// Image: /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera

- (id)makeSerializable;

// Image: /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit

// NSMutableDictionary (CKPropertiesDescription)

- (void)CKAddPropertySafelyForKey:(id)arg1 value:(id)arg2;

// NSMutableDictionary (CKUtilsAdditions)

- (void)CKSynchronizedRemoveObjectForKey:(id)arg1;
- (BOOL)CKSynchronizedSetIfAbsentObject:(id)arg1 forKey:(id)arg2;

// Image: /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList

// NSMutableDictionary (SFL)

- (void)_SFL_removeNSNullValues;
- (void)_SFL_setObjectOrNil:(id)arg1 forKey:(id)arg2;
- (void)_SFL_setTimeInterval:(double)arg1 forKey:(id)arg2;

// Image: /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording

// NSMutableDictionary (CDTextItems)

- (id)cueFileCDTextItems;

// Image: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

// NSMutableDictionary (NSDeprecatedKeyValueCoding)

- (void)takeValue:(id)arg1 forKey:(id)arg2;

// NSMutableDictionary (NSKeyValueCoding)

- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)takeStoredValue:(id)arg1 forKey:(id)arg2;

// NSMutableDictionary (NSMutableDictionary)

- (Class)classForCoder;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1 error:(id*)arg2;

// NSMutableDictionary (NSURLExtras)

- (void)_web_setBool:(BOOL)arg1 forKey:(id)arg2;
- (void)_web_setInt:(int)arg1 forKey:(id)arg2;
- (void)_web_setObject:(id)arg1 forUncopiedKey:(id)arg2;

// Image: /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

// NSMutableDictionary (NSOBEXHeaderUtilities)

+ (id)dictionaryWithOBEXHeadersData:(id)arg1;
+ (id)dictionaryWithOBEXHeadersData:(const void*)arg1 headersDataSize:(unsigned long long)arg2;
+ (id)withOBEXHeadersData:(const void*)arg1 headersDataSize:(unsigned long long)arg2;

- (int)addApplicationParameterHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addAuthorizationChallengeHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addAuthorizationResponseHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addBodyHeader:(const void*)arg1 length:(unsigned int)arg2 endOfBody:(BOOL)arg3;
- (int)addByteSequenceHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addConnectionIDHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addCountHeader:(unsigned int)arg1;
- (int)addDescriptionHeader:(id)arg1;
- (int)addHTTPHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addImageDescriptorHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addImageHandleHeader:(id)arg1;
- (int)addLengthHeader:(unsigned int)arg1;
- (int)addNameHeader:(id)arg1;
- (int)addObjectClassHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addTargetHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addTime4ByteHeader:(unsigned int)arg1;
- (int)addTimeISOHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addTypeHeader:(id)arg1;
- (int)addUserDefinedHeader:(const void*)arg1 length:(unsigned int)arg2;
- (int)addWhoHeader:(const void*)arg1 length:(unsigned int)arg2;
- (id)getHeaderBytes;

// Image: /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard

// NSMutableDictionary (BaseBoard)

- (void)bs_setSafeObject:(id)arg1 forKey:(id)arg2;
- (id)bs_takeObjectForKey:(id)arg1;

// Image: /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages

// NSMutableDictionary (MutableDictionaryExtensions)

- (BOOL)addKeyValuePairFromString:(id)arg1;

// Image: /System/Library/PrivateFrameworks/IMFoundation.framework/Versions/A/IMFoundation

+ (id)nonRetainingDictionary;
+ (id)nonRetainingKeyAndValueDictionary;
+ (id)retainingKeyDictionary;

// Image: /System/Library/PrivateFrameworks/OSAnalytics.framework/Versions/A/OSAnalytics

// NSMutableDictionary (OSALogCounterExtension)

- (void)osa_logCounter_countLogTypes_internal:(id)arg1 forOwner:(id)arg2;
- (unsigned long long)osa_logCounter_getForSubtype:(id)arg1 forOwner:(id)arg2;
- (void)osa_logCounter_incrementForSubtype:(id)arg1 signature:(id)arg2 filepath:(const char *)arg3;
- (void)osa_logCounter_incrementForSubtype_internal:(id)arg1 signature:(id)arg2 filepath:(const char *)arg3;
- (BOOL)osa_logCounter_isLog:(id)arg1 byKey:(id)arg2 count:(unsigned long long*)arg3 withinLimit:(unsigned long long*)arg4 withOptions:(id)arg5;
- (void)osa_logCounter_recordNixedDuplicate:(const char *)arg1;

// NSMutableDictionary (OSAStackshotKCDataExtension)

- (void)addTurnstileInfoDesc:(struct stackshot_thread_turnstileinfo { unsigned long long x1; unsigned long long x2; unsigned char x3; unsigned char x4; unsigned long long x5; }*)arg1 count:(unsigned int)arg2;
- (void)addWaitInfoDesc:(struct stackshot_thread_waitinfo { unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned char x4; }*)arg1 count:(unsigned int)arg2;

// Image: /System/Library/PrivateFrameworks/SystemAdministration.framework/Versions/A/SystemAdministration

// NSMutableDictionary (ADMLocalUser)

- (void)setObjectIfExists:(id)arg1 forKey:(id)arg2;

@end
